const TEMPLATES = {
forklift: {label:"Forklift / Telehandler", tpls:[
 {code:"FM/PE/011",title:"Daily / Weekly",items:[
  "D1 Check engine oil level","D2 Check radiator coolant level","D3 Check transmission oil level","D4 Check Hydraulic oil level","D5 Check air cleaner element / clean if dusty","D6 Check fan belt tension","D7 Check engine mountings","D8 Check Transmission mounting","D9 Check all hoses/fittings","D10 Drain fuel water separator","D11 Check Pins & joints for wear & tear","D12 Check for any leaks","D13 Check electrical/gauges","D14 Check for any abnormal sounds",
  "W1 Repeat above all","W2 Clean air cleaner element","W3 Check Battery electrolyte","W4 Check Engine Breather, clean if necessary","W5 Check for proper Brakes","W6 Check for proper Steering","W7 Check condition of Mast/Forks","W8 Check for any body cracks/damages","W9 Lubricate all joints/pins","W10 Lubricate U J Cross","W11 Lubricate Engine Water Pump bearing","W12 Service the Machine"]},
 {code:"FM/PE/062",title:"250 Hrs / Monthly",items:["Carry out weekly maintenance","Renew Engine Oil","Replace Engine Oil Filter","Replace Fuel Filter","Replace Fuel Water Separator Element","Check Fan Belt Tension/damage","Inspect Differential Oil Level","Test Braking System","Test Steering System"]},
 {code:"FM/PE/063",title:"500 Hrs / 3 Months",items:["Carry out 250 hrs maintenance","Replace Air Filter Primary","Replace Air Filter Secondary","Replace Hydraulic Oil Filter","Replace Transmission Oil Filter","Replace Corrossion Resistor","Clean Fuel tank cap & strainer","Clean Transmission & Hydraulic Breather","Clean Engine Crankcase Breather","Clean Radiator Fins","Inspect Engine Mountings"]},
 {code:"FM/PE/064",title:"1000 Hrs / 6 Months",items:["Carry out 250 & 500 hrs maintenance","Renew Transmission oil","Renew Differential Oil","Inspect Mast Rollers","Inspect Drive Shaft & Joints"]}
]},
crane: {label:"Mobile Crane", tpls:[
 {code:"FM/PE/017",title:"250 Hrs / Monthly",items:["Carry out weekly maintenance","Renew Engine Oil","Replace Engine Oil Filter","Replace Fuel Filter","Replace Fuel Water Separator","Inspect the clogged status of Hydraulic Oil Filters of Closed Pump Hydraulic Oil Filter & Return line filter","Inspect Slewing Ring Bearing & Mounting Bolts","Inspect Slewing Ring Tooth face & Lubricate","Inspect Slewing Table for any Cracks/defects","Inspect Hoist Mechanism; check the wire rope on the drum winds uniformly","Inspect the apperance & lubricating condition of Wire Rope","Inspect & conduct the Telescoping system function test","Inspect the cable reel for proper seating","Inspect & Conduct Counterweight Handler functional Test","Inspect the Counterweights","Inspect Main Boom for any cracks, deformation, misalignment etc.","Inspect the Jib for any crack/deformations","Check & Inspect all mounting fixtures for its tightness"]},
 {code:"FM/PE/018",title:"500 Hrs / 3 Months",items:["Carry out 250 hrs maintenance","Replace Transfer Case Oil","Replace Axle Case Oil","Replace Gear Oil of Main Winch, Auxiliary Winch & Luffing Winch","Replace Swing Gear Oil","Replace Air Filter Primary","Replace Air Filter Secondary","Replace Main High Pressure Hydraulic Oil Filters","Replace Return line Hydraulic Oil Filter","Replace Hydraulic Oil Filter of Closed Slewing Pump","Replace Hydraulic Oil Filter of Main Winch Pump","Replace Hydraulic Oil Filter of Luffing Winch Pump, if any","Replace Transmission Oil Filter","Replace Air Dryer Element","Replace Corrossion Resistor","Inspect Clutch Brake Fluid Quality & Replace if necessary","Clean Fuel tank cap & strainer","Clean Transmission & Hydraulic Breather","Clean Engine Crankcase Breather","Clean Ventilation Plugs of Transmission","Clean Radiator & Intercooler Fins","Inspect Engine Mountings","Inspect Fuel System Components & Hoses","Inspect Steering system components","Inspect Brake system components & Brake performance","Inspect Suspension Cylinder and Sensors","Inspect Suspension Energy Accumulator","Inspect Suspension Control Valve","Inspect & Ensure Outrigger Telescoping Mechanism","Inspect Hoist Mechanism","Inspect Hook Block - Pulley, Bearing, Hook etc.","Inspect and Lubricate UJ Cross & Propeller Shaft","Check Wheel Alignment","Inspect Air Conditioning system","Lubricate all the joints & Pins","Inspect and lubricate the oil pump drive device"]},
 {code:"FM/PE/019",title:"1000 Hrs / 6 Months",items:["Carry out 250 & 500 hrs maintenance","Renew Transmission oil","Renew Transfer Case Oil","Renew Drive Axle Oil","Renew Differential Oil","Renew Engine Coolant","Replace High Temperature Hose of Air Pump","Inspect Battery","Inspect all Hoses & fittings, replace if necessary","Inspect Brake Liners, Brake Shoe & Brake Drum for Wear & Tear","Lubricate Telescoping System Slide Block Surface"]}
]},
lmv: {label:"Light Motor Vehicle", tpls:[
 {code:"FM/PE/021",title:"5000 KM / Monthly",items:["Carry Out Weekly Maintenance","Renew Engine Oil","Replace Engine Oil Filter","Inspect air cleaner element/clean","Inspect Drive Belt Tension/ Damage","Check Gear Box/ Differential Oil","Inspect Steering function/Wheel Play","Inspect steering box linkage & boots/ Lower arm joint","Inspect Brake pads, Calipers and Rotors for wear & tear","Inspect Drive Shaft & Boots","Inspect Spark Plug/ Ignition Wires (Petrol Engine)"]},
 {code:"FM/PE/022",title:"10000 KM / 6 Months",items:["Carry Out 5000 KMS Maintenance","Replace Fuel Filter Element","Replace Automatic Transmission oil filter if any","Replace Air Cleaner Element","Inspect Fuel Line & Connections","Inspect Exhaust system damages","Inspect condition of clutch & brake fluid, replace if necessary","Inspect Power Steering System function/oil leakage","Inspect Brake Hoses & Lines","Inspect Parking Brake Cable/ Lever travel","Inspect Parking Brake Function","Inspect Suspension system for any Tight/Damage","Inspect A/C Operation/Refrigerant","Check Specific Gravity of Battery Electrolyte","Inspect Tyres for tread wear/ damage"]},
 {code:"FM/PE/023",title:"20000 KMS",items:["Carry Out 5000 & 10000 KMS Maintenance","Renew Automatic Transmission Fluid/ Filter","Renew Power Steering Fluid","Inspect / Replace Fan Belt","Adjust Intake & Exhaust Valve Clearance","Adjust Ignition Timing","Check Engine Smoke and replace Spark Plug if necessary (Petrol Engine)","Check for engine Smoke and Calibrate Fuel Injector if necessary (Diesel Engine)"]}
]},
hmv: {label:"Heavy Motor Vehicle", tpls:[
 {code:"FM/PE/025",title:"5000 KM / Monthly",items:["Carry Out Weekly Maintenance","Renew Engine Oil","Replace Engine Oil Filter","Inspect air cleaner element/ clean","Inspect Drive Belt Tension/ Damage","Check Gear Box/ Differential Oil","Inspect Steering function/Wheel Play","Inspect steering box linkage & boots/ Lower arm joint","Inspect Brake pads/Liners, Calipers and Rotors for wear & tear","Lubricate King Pin","Inspect Spark Plug/ Ignition Wires (Petrol Engine)"]},
 {code:"FM/PE/026",title:"10000 KM / 6 Months",items:["Carry Out 5000 KMS Maintenance","Replace Fuel Filter Element","Replace Fuel Water Seperator Element","Replace Automatic Transmission Oil Filter","Replace Air Cleaner Element Primary","Replace Air Cleaner Element Secondary","Replace Corrossion Resistor; if any","Inspect Fuel Line & Connections","Inspect Exhaust system damages","Inspect condition of clutch & brake fluid, replace if necessary","Inspect Power Steering System function/oil leakage","Inspect Brake Hoses & Lines","Inspect Parking Brake Cable/ Lever travel","Inspect Parking Brake Function","Inspect Suspension system for any Tight/Damage","Inspect A/C Operation/Refrigerant if any","Check Specific Gravity of Battery Electrolyte","Inspect Tyres for tread wear/damage"]},
 {code:"FM/PE/029",title:"20000 KM / 1000 Hrs",items:["Carry Out Weekly Maintenance","Renew Engine Oil","Replace Engine Oil Filter","Replace Fuel Filter","Inspect/Replace Fuel Water Seperator; if necessary","Inspect/Replace A/c Dust Filter; if necessary","Inspect air cleaner element/ clean","Inspect Drive Belt Tension/ Damage","Check Gear Box/ Differential Oil","Inspect Steering function/Wheel Play","Inspect steering box linkage & boots/ Lower arm joint","Inspect Brake pads/Liners, Calipers and Rotors for wear & tear","Lubricate King Pin","Check all Electricals/ Instrument panel","Check Specific Gravity of Battery Electrolyte","Reset all maintenance data"]}
]},
loader: {label:"Wheel Loader", tpls:[
 {code:"FM/PE/040",title:"250 Hrs / Monthly",items:["Carry out weekly maintenance","Renew Engine Oil","Replace Engine Oil Filter","Replace Fuel Filter","Clean Crankcase Breather","Check Fan Belt Tension/damage","Inspect Final Drive Oil Level","Test Braking System","Lubricate Fan Drive Pulley","Lubricate Drive Shaft Spline"]},
 {code:"FM/PE/041",title:"500 Hrs / 3 Months",items:["Carry out 250 hrs maintenance","Replace Fuel Water Seperator Element, if any","Replace Air Filter Primary","Replace Air Filter Secondary","Replace Hydraulic Oil Filter","Replace Transmission Oil Filter","Replace Corrossion Resistor; if any","Replace Engine Crankcase Breather Element","Clean Fuel tank cap & strainer","Clean Radiator Fins","Inspect Engine Mountings"]},
 {code:"FM/PE/042",title:"1000 Hrs / 6 Months",items:["Carry out 250 & 500 hrs maintenance","Renew Transmission Oil","Clean Transmission Magnetic Screens","Check & Adjust Engine Valve Lash"]}
]},
generator: {label:"Power Generator / Welding Generator", tpls:[
 {code:"FM/PE/070",title:"250 Hrs / Monthly",items:["Carry out weekly maintenance","Renew Engine Oil","Replace Engine Oil Filter","Replace Fuel Filter","Replace Fuel Water Separator Element","Check Fan Belt Tension/damage","Inspect Alternator Cooling Fan","Inspect Engine & Alternator Mountings","Clean Electronic Parts with Contact Cleaner"]},
 {code:"FM/PE/071",title:"500 Hrs / 3 Months",items:["Carry out 250 hrs maintenance","Replace Air Filter Primary","Replace Air Filter Secondary","Replace Corrossion Resistor","Inspect Crankshaft Vibration Damper","Inspect/Clean/Tight Earth Stud","Clean Fuel tank cap & strainer","Clean Engine Crankcase Breather","Clean Radiator Fins","Inspect the CT coil","Inspect the breaker","Inspect the armature","Electrical inspection","Inspect the battery","Inspect the starter motor"]}
]}
};
